
cd /home/projects/ssi_gen1/data/UKbiobank/genotype/SAIGE/MAFge05padj
for i in {1..22}; do /services/tools/gcta/1.26.0/bin/gcta64 --bfile /home/projects/ssi_gen1/data/UKbiobank/genotype/SAIGE/ukb_imp_chr"$i"_v3_15kSamples_info0.8_mac20 --chr $i --maf 0.001 --cojo-file FINALVENTRallMAFge05padj_to_GCTA.txt --cojo-slct --cojo-p 1e-5 --out chr"$i"_FINALVENTRallMAFge05padj_cojo-slct_p1e-5 & done; wait 
for i in {1..22}; do /services/tools/gcta/1.26.0/bin/gcta64 --bfile /home/projects/ssi_gen1/data/UKbiobank/genotype/SAIGE/ukb_imp_chr"$i"_v3_15kSamples_info0.8_mac20 --chr $i --maf 0.001 --cojo-file FINALUMBallMAFge05padj_to_GCTA.txt --cojo-slct --cojo-p 1e-5 --out chr"$i"_FINALUMBallMAFge05padj_cojo-slct_p1e-5 & done; wait 
for i in {1..22}; do /services/tools/gcta/1.26.0/bin/gcta64 --bfile /home/projects/ssi_gen1/data/UKbiobank/genotype/SAIGE/ukb_imp_chr"$i"_v3_15kSamples_info0.8_mac20 --chr $i --maf 0.001 --cojo-file FINALSPEC5allMAFge05padj_to_GCTA.txt --cojo-slct --cojo-p 1e-5 --out chr"$i"_FINALSPEC5allMAFge05padj_cojo-slct_p1e-5 & done; wait 
for i in {1..22}; do /services/tools/gcta/1.26.0/bin/gcta64 --bfile /home/projects/ssi_gen1/data/UKbiobank/genotype/SAIGE/ukb_imp_chr"$i"_v3_15kSamples_info0.8_mac20 --chr $i --maf 0.001 --cojo-file FINALnewINGbroadallMAFge05padj_to_GCTA.txt --cojo-slct --cojo-p 1e-5 --out chr"$i"_FINALnewINGbroadallMAFge05padj_cojo-slct_p1e-5 & done; wait 
for i in {1..22}; do /services/tools/gcta/1.26.0/bin/gcta64 --bfile /home/projects/ssi_gen1/data/UKbiobank/genotype/SAIGE/ukb_imp_chr"$i"_v3_15kSamples_info0.8_mac20 --chr $i --maf 0.001 --cojo-file FINALFEMallMAFge05padj_to_GCTA.txt --cojo-slct --cojo-p 1e-5 --out chr"$i"_FINALFEMallMAFge05padj_cojo-slct_p1e-5 & done; wait 
for i in {1..22}; do /services/tools/gcta/1.26.0/bin/gcta64 --bfile /home/projects/ssi_gen1/data/UKbiobank/genotype/SAIGE/ukb_imp_chr"$i"_v3_15kSamples_info0.8_mac20 --chr $i --maf 0.001 --cojo-file FINALFANTA4allMAFge05padj_to_GCTA.txt --cojo-slct --cojo-p 1e-5 --out chr"$i"_FINALFANTA4allMAFge05padj_cojo-slct_p1e-5 & done; wait 
for i in {1..22}; do /services/tools/gcta/1.26.0/bin/gcta64 --bfile /home/projects/ssi_gen1/data/UKbiobank/genotype/SAIGE/ukb_imp_chr"$i"_v3_15kSamples_info0.8_mac20 --chr $i --maf 0.001 --cojo-file FINALDIAallMAFge05padj_to_GCTA.txt --cojo-slct --cojo-p 1e-5 --out chr"$i"_FINALDIAallMAFge05padj_cojo-slct_p1e-5 & done; wait 

